--* veroneseInvariants_merged.m2
--
-- Helper functions for Veronese-type invariants in the cross-context coefficient slice.
--
-- For r = 2, the block-concatenated construction recovers the earlier 2 x 6
-- matrix obtained by horizontally concatenating the 2 x 2 catalecticant blocks
-- over all target index sets L for a fixed choice of context indices K.
--
-- The file generates three families of invariants:
--
--   1. internal
--      For each fixed pair (K,L), form the catalecticant matrix C_{K,L} and
--      take all 2 x 2 minors.
--
--   2. crossTarget
--      For each fixed K and each pair of distinct target index sets L,L',
--      form the matrix whose rows are indexed by degree-r multi-indices alpha
--      and whose two columns are D_{alpha,L} and D_{alpha,L'}. Take all
--      2 x 2 minors.
--
--   3. blockConcatenated
--      For each fixed K, concatenate the catalecticant blocks C_{K,L}
--      horizontally over all target index sets L, and take all 2 x 2 minors
--      of the resulting matrix. This includes the internal and cross-target
--      relations, together with additional mixed minors across different
--      blocks.
--
--   4. all
--      The sum of the three families above.
--
-- Assumptions:
--
--   1. We work in a single fixed output coordinate, so d' = 1.
--   2. myRing is the ambient coefficient ring generated by the y-variables.
--   3. idxList records the monomial labels used to index those generators.
--   4. The rank parameter satisfies 2 <= r <= min(d,at).
--
-- Output:
--
--   makeVeroneseInvariants(myRing, idxList, d, t, at, j, r)
--   returns a hash table H with entries
--
--     H#"internal"
--     H#"crossTarget"
--     H#"blockConcatenated"
--     H#"strengthened"   -- alias for blockConcatenated
--     H#"all"
--
--   together with raw and trimmed generator counts.
--
--   makeAllVeroneseInvariants(myRing, idxList, d, t, at, j)
--   sums these ideals over r = 2, ..., min(d,at).
--
--*


makeVeroneseInvariants = (myRing, idxList, d, t, at, j, r) -> (

    if j < 1 or j > t then error("j must lie in [1..t]");
    if r < 2 then error("r must be at least 2");
    if r > d then error("r must be at most d");
    if r > at then error("r must be at most at");

    alphas := compositions(r, r);
    betas  := compositions(r, 1);
    gammas := compositions(r, r - 1);
    rSubsets := apply(subsets(toList(1..d), r), s -> toList s);

    alphaKey := alpha -> toString alpha;
    pairKey  := (K, Lset) -> toString K | "|" | toString Lset;
    addVec   := (u, v) -> apply(#u, i -> u#i + v#i);
    omega    := (u, v) -> if u == v then 1 else 2;

    -- fast lookup from monomial label to ambient variable
    varTable := new MutableHashTable;
    scan(#idxList, p -> (
        varTable#(toString(idxList#p)) = (gens myRing)_p;
    ));

    crossLabel := (a, b, c, n, jj) -> toSequence sort {(a,n),(b,n),(c,jj)};

    coeffVar := (a, b, c, n, jj) -> (
        key := toString crossLabel(a, b, c, n, jj);
        if not varTable#?key then error("label not found: " | key);
        varTable#key
    );

    -- acyclic map f used in Theorem 30
    makeF := alpha -> (
        deficits := flatten apply(r, m -> toList(max(0, alpha#m - 1) : (m+1)));
        z := 0;
        apply(r, p -> (
            if alpha#p > 0 then p + 1
            else (
                val := deficits#z;
                z = z + 1;
                val
            )
        ))
    );

    Dalpha := (K, Lset, alpha, n, jj) -> (
        f := makeF alpha;
        M := matrix apply(r, p -> (
            apply(r, q -> (
                u   := K#(f#p - 1);
                v   := K#p;
                ell := Lset#q;
                omega(u, v) * coeffVar(u, v, ell, n, jj)
            ))
        ));
        det M
    );

    catalecticantFromDtab := Dtab -> (
        matrix apply(betas, beta -> (
            apply(gammas, gamma -> Dtab#(alphaKey addVec(beta, gamma)))
        ))
    );

    makeIdeal := rels -> (
        good := select(rels, f -> f =!= 0_myRing);
        if #good == 0 then ideal(0_myRing) else ideal good
    );

    numMGens := I -> #flatten entries mingens I;

    internalRels := {};
    crossTargetRels := {};
    blockConcatenatedRels := {};

    for n from 1 to t do (
        if n =!= j then (
            for K in rSubsets do (

                -- cache all D_alpha(K,L;n,j) for this fixed K and all L
                Dtabs := new MutableHashTable;
                scan(rSubsets, Lset -> (
                    T := new MutableHashTable;
                    scan(alphas, alpha -> (
                        T#(alphaKey alpha) = Dalpha(K, Lset, alpha, n, j);
                    ));
                    Dtabs#(pairKey(K, Lset)) = T;
                ));

                ----------------------------------------------------
                -- (1) INTERNAL: 2x2 minors inside each catalecticant block
                ----------------------------------------------------
                scan(rSubsets, Lset -> (
                    T := Dtabs#(pairKey(K, Lset));
                    C := catalecticantFromDtab T;
                    internalRels = internalRels | flatten entries gens minors(2, C);
                ));

                ----------------------------------------------------
                -- (2) COROLLARY 31: pairwise cross-target minors
                ----------------------------------------------------
                scan(subsets(rSubsets, 2), pair -> (
                    Lset1 := pair#0;
                    Lset2 := pair#1;
                    T1 := Dtabs#(pairKey(K, Lset1));
                    T2 := Dtabs#(pairKey(K, Lset2));

                    Mpair := matrix apply(alphas, alpha -> {
                        T1#(alphaKey alpha),
                        T2#(alphaKey alpha)
                    });

                    crossTargetRels = crossTargetRels | flatten entries gens minors(2, Mpair);
                ));

                ----------------------------------------------------
                -- (3) STRENGTHENED FAMILY: concatenate all blocks C_{K,L}
                ----------------------------------------------------
                bigRows := apply(betas, beta -> (
                    flatten apply(rSubsets, Lset -> (
                        T := Dtabs#(pairKey(K, Lset));
                        apply(gammas, gamma -> T#(alphaKey addVec(beta, gamma)))
                    ))
                ));

                bigC := matrix bigRows;
                blockConcatenatedRels = blockConcatenatedRels | flatten entries gens minors(2, bigC);
            )
        )
    );

    internalIdeal := trim makeIdeal internalRels;
    crossTargetIdeal := trim makeIdeal crossTargetRels;
    blockConcatenatedIdeal := trim makeIdeal blockConcatenatedRels;
    allIdeal := trim(internalIdeal + crossTargetIdeal + blockConcatenatedIdeal);

    H := new MutableHashTable;
    H#"internal" = internalIdeal;
    H#"crossTarget" = crossTargetIdeal;
    H#"blockConcatenated" = blockConcatenatedIdeal;
    H#"strengthened" = blockConcatenatedIdeal;
    H#"all" = allIdeal;

    H#"internalRawCount" = #internalRels;
    H#"crossTargetRawCount" = #crossTargetRels;
    H#"blockConcatenatedRawCount" = #blockConcatenatedRels;
    H#"allRawCount" = #internalRels + #crossTargetRels + #blockConcatenatedRels;

    H#"internalCount" = numMGens internalIdeal;
    H#"crossTargetCount" = numMGens crossTargetIdeal;
    H#"blockConcatenatedCount" = numMGens blockConcatenatedIdeal;
    H#"allCount" = numMGens allIdeal;

    H
);

makeAllVeroneseInvariants = (myRing, idxList, d, t, at, j) -> (
    Hall := new MutableHashTable;
    Hall#"internal" = ideal(0_myRing);
    Hall#"crossTarget" = ideal(0_myRing);
    Hall#"blockConcatenated" = ideal(0_myRing);
    Hall#"strengthened" = ideal(0_myRing);
    Hall#"all" = ideal(0_myRing);

    for r from 2 to min(d, at) do (
        Hr := makeVeroneseInvariants(myRing, idxList, d, t, at, j, r);
        Hall#"internal" = trim(Hall#"internal" + Hr#"internal");
        Hall#"crossTarget" = trim(Hall#"crossTarget" + Hr#"crossTarget");
        Hall#"blockConcatenated" = trim(Hall#"blockConcatenated" + Hr#"blockConcatenated");
        Hall#"strengthened" = Hall#"blockConcatenated";
        Hall#"all" = trim(Hall#"all" + Hr#"all");
    );

    Hall
);